{
 "title": "RPI4",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "PRAGMA read_uncommitted = 1;\nSELECT \n CPUStatAll \nFROM \n tkmSysProcStat NOLOCK \nWHERE CPUStatName = 'cpu' AND ReceiveTime > ${__from:date:seconds} ORDER BY ReceiveTime DESC LIMIT 1;",
     "rawQueryText": "PRAGMA read_uncommitted = 1;\nSELECT \n CPUStatAll \nFROM \n tkmSysProcStat NOLOCK \nWHERE CPUStatName = 'cpu' AND ReceiveTime > ${__from:date:seconds} ORDER BY ReceiveTime DESC LIMIT 1;",
     "source": "url",
     "timeColumns": [ "ReceiveTime" ],
     "type": "json",
     "url": "https://jsonplaceholder.typicode.com/users",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "MEM Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "PRAGMA read_uncommitted = 1;\nSELECT \n 100 - MemAvailPercent \nFROM tkmSysProcMeminfo  NOLOCK \nWHERE ReceiveTime > ${__from:date:seconds} ORDER BY ReceiveTime DESC LIMIT 1;",
     "rawQueryText": "PRAGMA read_uncommitted = 1;\nSELECT \n 100 - MemAvailPercent \nFROM tkmSysProcMeminfo  NOLOCK \nWHERE ReceiveTime > ${__from:date:seconds} ORDER BY ReceiveTime DESC LIMIT 1;",
     "timeColumns": [ "ReceiveTime" ]
    }
   ]
  },
  {
   "title": "SWAP Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "PRAGMA read_uncommitted = 1;\nSELECT \n  100 - SwapFreePercent \nFROM tkmSysProcMeminfo  NOLOCK \nWHERE ReceiveTime > ${__from:date:seconds} ORDER BY ReceiveTime DESC LIMIT 1;",
     "rawQueryText": "PRAGMA read_uncommitted = 1;\nSELECT \n  100 - SwapFreePercent \nFROM tkmSysProcMeminfo  NOLOCK \nWHERE ReceiveTime > ${__from:date:seconds} ORDER BY ReceiveTime DESC LIMIT 1;",
     "timeColumns": [ "ReceiveTime" ]
    }
   ]
  },
  {
   "title": "CPU History",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 15, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "queryText": "PRAGMA read_uncommitted = 1;\nSELECT\n   ReceiveTime,\n   CPUStatAll as 'all',\n   CPUStatUsr as 'usr',\n   CPUStatSys as 'sys'\nFROM \n   tkmSysProcStat  NOLOCK \nWHERE CPUStatName = 'cpu' AND ReceiveTime > ${__from:date:seconds} ORDER BY ReceiveTime;",
     "rawQueryText": "PRAGMA read_uncommitted = 1;\nSELECT\n   ReceiveTime,\n   CPUStatAll as 'all',\n   CPUStatUsr as 'usr',\n   CPUStatSys as 'sys'\nFROM \n   tkmSysProcStat  NOLOCK \nWHERE CPUStatName = 'cpu' AND ReceiveTime > ${__from:date:seconds} ORDER BY ReceiveTime;",
     "source": "url",
     "timeColumns": [ "ReceiveTime" ],
     "type": "json",
     "url": "https://jsonplaceholder.typicode.com/users",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Process Events",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 5 },
   "targets": [
    {
     "queryText": "PRAGMA read_uncommitted = 1;\nSELECT \n ReceiveTime,\n ForkCount,\n ExecCount,\n ExitCount,\n UIdCount,\n GIdCount \nFROM tkmProcEvent NOLOCK  \nWHERE ReceiveTime > ${__from:date:seconds} ORDER BY 1;",
     "rawQueryText": "PRAGMA read_uncommitted = 1;\nSELECT \n ReceiveTime,\n ForkCount,\n ExecCount,\n ExitCount,\n UIdCount,\n GIdCount \nFROM tkmProcEvent NOLOCK  \nWHERE ReceiveTime > ${__from:date:seconds} ORDER BY 1;",
     "timeColumns": [ "ReceiveTime" ]
    }
   ]
  },
  {
   "title": "Memory History",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 15, "x": 9, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "queryText": "PRAGMA read_uncommitted = 1;\nSELECT\n   ReceiveTime,\n   MemTotal,\n   MemFree,\n   MemAvail,\n   SwapTotal,\n   SwapFree\nFROM \n   tkmSysProcMeminfo NOLOCK \nWHERE ReceiveTime > ${__from:date:seconds} ORDER BY ReceiveTime;",
     "rawQueryText": "PRAGMA read_uncommitted = 1;\nSELECT\n   ReceiveTime,\n   MemTotal,\n   MemFree,\n   MemAvail,\n   SwapTotal,\n   SwapFree\nFROM \n   tkmSysProcMeminfo NOLOCK \nWHERE ReceiveTime > ${__from:date:seconds} ORDER BY ReceiveTime;",
     "timeColumns": [ "ReceiveTime" ]
    }
   ]
  },
  {
   "title": "System Pressure",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "queryText": "PRAGMA read_uncommitted = 1;\nSELECT \n ReceiveTime,\n CPUSomeAvg10,\n MEMSomeAvg10,\n IOSomeAvg10,\n CPUSomeAvg60,\n MEMSomeAvg60,\n IOSomeAvg60 \nFROM tkmSysProcPressure NOLOCK  \nWHERE ReceiveTime > ${__from:date:seconds} ORDER BY 1;",
     "rawQueryText": "PRAGMA read_uncommitted = 1;\nSELECT \n ReceiveTime,\n CPUSomeAvg10,\n MEMSomeAvg10,\n IOSomeAvg10,\n CPUSomeAvg60,\n MEMSomeAvg60,\n IOSomeAvg60 \nFROM tkmSysProcPressure NOLOCK  \nWHERE ReceiveTime > ${__from:date:seconds} ORDER BY 1;",
     "source": "url",
     "timeColumns": [ "ReceiveTime" ],
     "type": "json",
     "url": "https://jsonplaceholder.typicode.com/users",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Context CPU Stats",
   "type": "barchart",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "queryText": "PRAGMA read_uncommitted = 1;\nSELECT DISTINCT\nContextName,TotalCpuPercent\nFROM tkmContextInfo NOLOCK\nWHERE  ${__to:date:seconds} - ReceiveTime < 10\nGROUP BY ContextId LIMIT 100;",
     "rawQueryText": "PRAGMA read_uncommitted = 1;\nSELECT DISTINCT\nContextName,TotalCpuPercent\nFROM tkmContextInfo NOLOCK\nWHERE  ${__to:date:seconds} - ReceiveTime < 10\nGROUP BY ContextId LIMIT 100;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Context MEM Usage",
   "type": "barchart",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "queryText": "PRAGMA read_uncommitted = 1;\nSELECT DISTINCT\nContextName,TotalVmRSS\nFROM tkmContextInfo NOLOCK\nWHERE  ${__to:date:seconds} - ReceiveTime < 10\nGROUP BY ContextId LIMIT 100;",
     "rawQueryText": "PRAGMA read_uncommitted = 1;\nSELECT DISTINCT\nContextName,TotalVmRSS\nFROM tkmContextInfo NOLOCK\nWHERE  ${__to:date:seconds} - ReceiveTime < 10\nGROUP BY ContextId LIMIT 100;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "CPU Usage Per Process",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "PRAGMA read_uncommitted = 1;\nSELECT DISTINCT\nComm,CpuPercent\nFROM tkmProcInfo NOLOCK\nWHERE  ${__to:date:seconds} - ReceiveTime < 10\nGROUP BY PID;",
     "rawQueryText": "PRAGMA read_uncommitted = 1;\nSELECT DISTINCT\nComm,CpuPercent\nFROM tkmProcInfo NOLOCK\nWHERE  ${__to:date:seconds} - ReceiveTime < 10\nGROUP BY PID;",
     "timeColumns": [
      "time",
      "ts",
      "ReceiveTime"
     ]
    }
   ]
  },
  {
   "title": "MEM Usage Per Process",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "PRAGMA read_uncommitted = 1;\nSELECT DISTINCT\nComm,VmRSS\nFROM tkmProcInfo NOLOCK\nWHERE  ${__to:date:seconds} - ReceiveTime < 10\nGROUP BY Comm LIMIT 100;",
     "rawQueryText": "PRAGMA read_uncommitted = 1;\nSELECT DISTINCT\nComm,VmRSS\nFROM tkmProcInfo NOLOCK\nWHERE  ${__to:date:seconds} - ReceiveTime < 10\nGROUP BY Comm LIMIT 100;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Process Info",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "queryText": "PRAGMA read_uncommitted = 1;\nSELECT DISTINCT\nReceiveTime,Comm,PID, PPID,ContextName,CpuTime,CpuPercent,VmRSS\nFROM tkmProcInfo NOLOCK\nWHERE  ${__to:date:seconds} - ReceiveTime < 5\nGROUP BY PID LIMIT 100;",
     "rawQueryText": "PRAGMA read_uncommitted = 1;\nSELECT DISTINCT\nReceiveTime,Comm,PID, PPID,ContextName,CpuTime,CpuPercent,VmRSS\nFROM tkmProcInfo NOLOCK\nWHERE  ${__to:date:seconds} - ReceiveTime < 5\nGROUP BY PID LIMIT 100;",
     "timeColumns": [
      "time",
      "ts",
      "ReceiveTime"
     ]
    }
   ]
  },
  {
   "title": "Context Info",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "queryText": "PRAGMA read_uncommitted = 1;\nSELECT DISTINCT\nReceiveTime,ContextName,TotalCpuTime,TotalCpuPercent,TotalVmRSS\nFROM tkmContextInfo NOLOCK\nWHERE  ${__to:date:seconds} - ReceiveTime < 10\nGROUP BY ContextId LIMIT 100;",
     "rawQueryText": "PRAGMA read_uncommitted = 1;\nSELECT DISTINCT\nReceiveTime,ContextName,TotalCpuTime,TotalCpuPercent,TotalVmRSS\nFROM tkmContextInfo NOLOCK\nWHERE  ${__to:date:seconds} - ReceiveTime < 10\nGROUP BY ContextId LIMIT 100;",
     "timeColumns": [
      "time",
      "ts",
      "ReceiveTime"
     ]
    }
   ]
  },
  {
   "title": "BuddyInfo",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "queryText": "PRAGMA read_uncommitted = 1;\nSELECT\nReceiveTime,Name,Zone,Data\nFROM tkmSysProcBuddyInfo NOLOCK\nWHERE  ${__to:date:seconds} - ReceiveTime < 15\nGROUP BY Zone LIMIT 100;",
     "rawQueryText": "PRAGMA read_uncommitted = 1;\nSELECT\nReceiveTime,Name,Zone,Data\nFROM tkmSysProcBuddyInfo NOLOCK\nWHERE  ${__to:date:seconds} - ReceiveTime < 15\nGROUP BY Zone LIMIT 100;",
     "timeColumns": [
      "time",
      "ts",
      "ReceiveTime"
     ]
    }
   ]
  },
  {
   "title": "Wireless Statistics",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "queryText": "PRAGMA read_uncommitted = 1;\nSELECT DISTINCT\nReceiveTime,Name,Status,QualityLink,QualityLevel,QualityNoise,DiscardedNWId,DiscardedCrypt,DiscardedFrag,DiscardedRetry,DiscardedMisc,MissedBeacon\nFROM tkmSysProcWireless NOLOCK\nWHERE  ${__to:date:seconds} - ReceiveTime < 15\nGROUP BY Name LIMIT 100;",
     "rawQueryText": "PRAGMA read_uncommitted = 1;\nSELECT DISTINCT\nReceiveTime,Name,Status,QualityLink,QualityLevel,QualityNoise,DiscardedNWId,DiscardedCrypt,DiscardedFrag,DiscardedRetry,DiscardedMisc,MissedBeacon\nFROM tkmSysProcWireless NOLOCK\nWHERE  ${__to:date:seconds} - ReceiveTime < 15\nGROUP BY Name LIMIT 100;",
     "timeColumns": [
      "time",
      "ts",
      "ReceiveTime"
     ]
    }
   ]
  },
  {
   "title": "Disks Stats",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {
     "queryText": "PRAGMA read_uncommitted = 1;\nSELECT DISTINCT\nReceiveTime,Major,Minor,Name,ReadsCompleted,ReadsMerged,ReadsSpent,WritesCompleted,WritesMerged,WritesSpent,IoInProgress,IoSpent,IoWeightedMs\nFROM tkmSysProcDiskStats NOLOCK\nWHERE ReceiveTime > ${__from:date:seconds} \nGROUP BY Name LIMIT 100;",
     "rawQueryText": "PRAGMA read_uncommitted = 1;\nSELECT DISTINCT\nReceiveTime,Major,Minor,Name,ReadsCompleted,ReadsMerged,ReadsSpent,WritesCompleted,WritesMerged,WritesSpent,IoInProgress,IoSpent,IoWeightedMs\nFROM tkmSysProcDiskStats NOLOCK\nWHERE ReceiveTime > ${__from:date:seconds} \nGROUP BY Name LIMIT 100;",
     "timeColumns": [
      "time",
      "ts",
      "ReceiveTime"
     ]
    }
   ]
  },
  {
   "title": "Process Accounting",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 47 },
   "targets": [
    {
     "queryText": "PRAGMA read_uncommitted = 1;\nSELECT DISTINCT\nReceiveTime,AcComm,AcUid,AcPid,AcPPid,AcUTime,AcSTime,CpuCount,CpuRunRealTotal,CpuRunVirtualTotal,CoreMem,VirtMem,IOReadChar,IOWriteChar,IOReadSyscalls,IOWriteSyscalls \nFROM tkmProcAcct NOLOCK\nWHERE ReceiveTime > ${__from:date:seconds} \nGROUP BY AcComm LIMIT 100;",
     "rawQueryText": "PRAGMA read_uncommitted = 1;\nSELECT DISTINCT\nReceiveTime,AcComm,AcUid,AcPid,AcPPid,AcUTime,AcSTime,CpuCount,CpuRunRealTotal,CpuRunVirtualTotal,CoreMem,VirtMem,IOReadChar,IOWriteChar,IOReadSyscalls,IOWriteSyscalls \nFROM tkmProcAcct NOLOCK\nWHERE ReceiveTime > ${__from:date:seconds} \nGROUP BY AcComm LIMIT 100;",
     "source": "url",
     "timeColumns": [ "ReceiveTime" ],
     "type": "json",
     "url": "https://jsonplaceholder.typicode.com/users",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  }
 ]
}