set(CPACK_PACKAGE_NAME ${PROJECT_NAME}
    CACHE STRING "Linux System Monitor"
)
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Linux System Monitor"
    CACHE STRING "A simple system service to collect performance indicators from embedded systems"
)
set(CPACK_PACKAGE_VENDOR "Alin Popa")

set(CPACK_VERBATIM_VARIABLES YES)

set(CPACK_PACKAGE_INSTALL_DIRECTORY ${CPACK_PACKAGE_NAME})
SET(CPACK_OUTPUT_FILE_PREFIX "${CMAKE_SOURCE_DIR}/packages")

set(CPACK_PACKAGE_VERSION_MAJOR ${PROJECT_VERSION_MAJOR})
set(CPACK_PACKAGE_VERSION_MINOR ${PROJECT_VERSION_MINOR})
set(CPACK_PACKAGE_VERSION_PATCH ${PROJECT_VERSION_PATCH})

set(CPACK_PACKAGE_CONTACT "alin.popa@fxdata.ro")
set(CPACK_DEBIAN_PACKAGE_MAINTAINER "Alin Popa")

set(CPACK_RESOURCE_FILE_LICENSE "${CMAKE_CURRENT_SOURCE_DIR}/LICENSE")
set(CPACK_RESOURCE_FILE_README "${CMAKE_CURRENT_SOURCE_DIR}/README.md")

# RPM
set(CPACK_RPM_CHANGELOG_FILE "${CMAKE_CURRENT_SOURCE_DIR}/CHANGELOG")
set(CPACK_RPM_PACKAGE_LICENSE "MIT")
set(CPACK_RPM_PACKAGE_GROUP "Applications/System")
set(CPACK_RPM_PACKAGE_REQUIRES "systemd >= 243, libnl3 >= 3.4.0, protobuf >= 3.14.0")

# DEB
set(CPACK_DEBIAN_FILE_NAME DEB-DEFAULT)
set(CPACK_DEBIAN_PACKAGE_SECTION "Utilities")
set(CPACK_DEBIAN_PACKAGE_DEPENDS "libsystemd (>= 243), libnl-3-200 (>= 3.4.0), libnl-genl-3-200 (>=3.5.0), libprotobuf23 (>=3.12.4)")

include(CPack)
